---
- name: Provision Grow Admin Server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    packages:
      - vim
      - git
      - python3-pip
      - nginx
  become: yes
  tasks:
    - name: Install packages
      apt:
        state: latest
        pkg: "{{ packages }}"
        update_cache: yes
        cache_valid_time: 3600
    - name: Checkout code from Github
      git:
        repo: https://github.com/frak/grow-python.git
        dest: /var/grow-python
        version: master
    - name: Install python dependencies
      pip:
        requirements: /var/grow-python/admin/requirements.txt
        executable: /usr/bin/pip3
