---
- name: Provision Grow Admin Server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    packages:
      - vim
      - git
      - python3-pip
    pip_packages:
      - django
      - djangorestframework
      - python-dotenv
  become: yes
  become_user: root
  tasks:
    - name: Install packages
      apt:
        state: latest
        pkg: "{{ packages }}"
        update_cache: yes
        cache_valid_time: 3600
    - name: Install python dependencies
      pip:
        name: "{{ pip_packages }}"
        executable: /usr/bin/pip3
    - name: Checkout code from Github
      git:
        repo: https://github.com/frak/grow-python.git
        dest: /var/grow-python
        version: ui-separation
