---
- name: Provision Grow Pi Device
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    admin_host: "{{ lookup('env', 'ADMIN_HOST') | default('admin.grow', true) }}"
    admin_ip: "{{ lookup('env', 'ADMIN_IP') | default('192.168.0.19', true) }}"
    packages:
      - vim
      - git
      - python3-pip
  become: yes
  become_user: root
  tasks:
    - name: Install packages
      apt:
        state: latest
        pkg: "{{ packages }}"
        update_cache: yes
        cache_valid_time: 3600
    - name: Checkout code from Github
      git:
        repo: https://github.com/frak/grow-python.git
        dest: /var/grow-python
        version: master
    - name: Install python dependencies
      pip:
        requirements: /var/grow-python/device/requirements.txt
        executable: /usr/bin/pip3
    - name: Creating runtime directory
      file:
        path: /var/lib/grow-monitor
        state: directory
    - name: Set /etc/hosts entry for admin server
      lineinfile:
        path: /etc/hosts
        line: "{{ admin_ip }} {{ admin_host }}"
    - name: Check if SPI is enabled
      command: raspi-config nonint get_spi
      register: has_spi
      changed_when: has_spi.stdout == "1"
    - name: Setup SPI
      command: raspi-config nonint do_spi 0
      when: has_spi.stdout == "1"
    - name: Check if I2C is enabled
      command: raspi-config nonint get_i2c
      register: has_i2c
      changed_when: has_i2c.stdout == "1"
    - name: Setup I2C
      command: raspi-config nonint do_i2c 0
      when: has_i2c.stdout == "1"
    - name: Set dtoverlay in /boot/config.txt
      lineinfile:
        path: /boot/config.txt
        line: dtoverlay=spi0-cs,cs0_pin=14
    - name: Copy service files
      template:
        src: "../service/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
      vars:
        unit_host: "{{ ansible_facts['hostname'] }}"
      with_items:
        - grow-monitor.service
        - grow-worker.service
        - grow-worker.timer
    - name: Start services
      systemd:
        state: restarted
        daemon_reload: yes
        name: "{{ item }}"
      with_items:
        - grow-monitor.service
        - grow-worker.timer
    - name: Register this provisioning with the admin server
      uri:
        url: "http://{{ admin_host}}/api/provision/{{ ansible_facts['hostname'] }}"
    - name: Reboot the device to apply changes
      reboot:
